export const KNOWLEDGE_BASE = {
  foods: {
    fruits: {
      apple: { name: "Apple", hindi: "सेब", cal: 52, p: 0.3, c: 14, f: 0.2, fiber: 2.4, gi: 36, benefits: ["Heart health", "Weight loss", "Digestive health"] },
      banana: { name: "Banana", hindi: "केला", cal: 89, p: 1.1, c: 23, f: 0.3, fiber: 2.6, gi: 51, benefits: ["Energy boost", "Muscle recovery", "Digestion"] },
      mango: { name: "Mango", hindi: "आम", cal: 60, p: 0.8, c: 15, f: 0.4, fiber: 1.6, gi: 51, benefits: ["Immunity", "Eye health", "Skin health"] },
      orange: { name: "Orange", hindi: "संतरा", cal: 47, p: 0.9, c: 12, f: 0.1, fiber: 2.4, gi: 43, benefits: ["Immunity", "Skin health", "Iron absorption"] },
      papaya: { name: "Papaya", hindi: "पपीता", cal: 43, p: 0.5, c: 11, f: 0.3, fiber: 1.7, gi: 60, benefits: ["Digestion", "Anti-inflammatory", "Skin health"] },
      watermelon: { name: "Watermelon", hindi: "तरबूज", cal: 30, p: 0.6, c: 8, f: 0.2, fiber: 0.4, gi: 72, benefits: ["Hydration", "Muscle recovery", "Citrulline"] },
      pomegranate: { name: "Pomegranate", hindi: "अनार", cal: 83, p: 1.7, c: 19, f: 1.2, fiber: 4, gi: 53, benefits: ["Heart health", "Blood flow", "Antioxidants"] },
      guava: { name: "Guava", hindi: "अमरूद", cal: 68, p: 2.6, c: 14, f: 1, fiber: 5.4, gi: 12, benefits: ["Vitamin C", "Fiber", "Immunity"] },
      pineapple: { name: "Pineapple", hindi: "अनानास", cal: 50, p: 0.5, c: 13, f: 0.1, fiber: 1.4, gi: 66, benefits: ["Bromelain", "Digestion"] },
      kiwi: { name: "Kiwi", cal: 61, p: 1.1, c: 15, f: 0.5, fiber: 3, gi: 53, benefits: ["Vitamin C", "Sleep quality"] },
    },
    vegetables: {
      spinach: { name: "Spinach", hindi: "पालक", cal: 23, p: 2.9, c: 3.6, f: 0.4, fiber: 2.2, gi: 15, iron: 2.7, benefits: ["Iron", "Eye health", "Bone health"] },
      broccoli: { name: "Broccoli", hindi: "हरी गोभी", cal: 34, p: 2.8, c: 7, f: 0.4, fiber: 2.6, gi: 10, benefits: ["Cancer prevention", "Bone health", "Immunity"] },
      cauliflower: { name: "Cauliflower", hindi: "फूलगोभी", cal: 25, p: 1.9, c: 5, f: 0.3, fiber: 2, gi: 15, benefits: ["Weight loss", "Low carb", "Detox"] },
      carrot: { name: "Carrot", hindi: "गाजर", cal: 41, p: 0.9, c: 10, f: 0.2, fiber: 2.8, gi: 39, benefits: ["Eye health", "Skin health", "Beta carotene"] },
      tomato: { name: "Tomato", hindi: "टमाटर", cal: 18, p: 0.9, c: 3.9, f: 0.2, fiber: 1.2, gi: 38, benefits: ["Lycopene", "Heart health", "Antioxidants"] },
      cucumber: { name: "Cucumber", hindi: "खीरा", cal: 15, p: 0.7, c: 3.6, f: 0.1, fiber: 0.5, water: 95, gi: 15, benefits: ["Hydration", "Weight loss", "Cooling"] },
      potato: { name: "Potato", hindi: "आलू", cal: 77, p: 2, c: 17, f: 0.1, fiber: 2.1, gi: 85, benefits: ["Potassium", "Energy", "Vitamin C"] },
      sweetPotato: { name: "Sweet Potato", hindi: "शकरकंद", cal: 86, p: 1.6, c: 20, f: 0.1, fiber: 3, gi: 63, benefits: ["Complex carbs", "Vitamin A", "Fiber"] },
      beetroot: { name: "Beetroot", hindi: "चुकंदर", cal: 43, p: 1.6, c: 10, f: 0.2, fiber: 2.8, gi: 61, benefits: ["Nitrates", "Endurance", "Blood flow"] },
      mushroom: { name: "Mushroom", hindi: "मशरूम", cal: 22, p: 3.1, c: 3.3, f: 0.3, fiber: 1, gi: 10, benefits: ["Vitamin D", "Protein", "Immunity"] },
    },
    proteins: {
      chickenBreast: { name: "Chicken Breast", hindi: "चिकन ब्रेस्ट", cal: 165, p: 31, c: 0, f: 3.6, benefits: ["Muscle building", "Weight loss", "Lean protein"] },
      egg_whole: { name: "Whole Egg", hindi: "अंडा", cal: 155, p: 13, c: 1.1, f: 11, benefits: ["Complete protein", "Vitamin D", "Choline"] },
      egg_white: { name: "Egg White", hindi: "अंडे की सफेदी", cal: 52, p: 11, c: 0.7, f: 0.2, benefits: ["Pure protein", "Fat free"] },
      salmon: { name: "Salmon", cal: 208, p: 20, c: 0, f: 13, omega3: 2.3, benefits: ["Omega-3", "Heart health", "Brain health"] },
      paneer: { name: "Paneer", hindi: "पनीर", cal: 265, p: 18, c: 3.4, f: 20, calcium: 200, benefits: ["Protein", "Calcium", "Vegetarian protein"] },
      tofu: { name: "Tofu", cal: 76, p: 8, c: 1.9, f: 4.8, calcium: 350, benefits: ["Vegan protein", "Low calorie", "Iron"] },
      lentils: { name: "Lentils", hindi: "दाल", cal: 116, p: 9, c: 20, f: 0.4, fiber: 8, benefits: ["Plant protein", "Fiber", "Iron"] },
      chickpeas: { name: "Chickpeas", hindi: "छोले", cal: 164, p: 8.9, c: 27, f: 2.6, fiber: 7.6, benefits: ["Protein", "Fiber", "Complex carbs"] },
      kidneyBeans: { name: "Kidney Beans", hindi: "राजमा", cal: 127, p: 8.7, c: 23, f: 0.5, fiber: 6.4, benefits: ["Protein", "Fiber", "Iron"] },
      almonds: { name: "Almonds", hindi: "बादाम", cal: 579, p: 21, c: 22, f: 50, fiber: 12.5, benefits: ["Healthy fats", "Vitamin E", "Brain health"] },
      walnuts: { name: "Walnuts", hindi: "अखरोट", cal: 654, p: 15, f: 65, omega3: 9.1, benefits: ["Omega-3", "Brain health", "Antioxidants"] },
      chiaSeed: { name: "Chia Seeds", cal: 486, p: 17, c: 42, f: 31, fiber: 34, omega3: 17.8, benefits: ["Omega-3", "Complete protein", "Fiber"] },
      wheyProtein: { name: "Whey Protein", cal: 120, p: 24, c: 3, f: 1.5, benefits: ["Fast absorption", "Post-workout", "Convenient"] },
    },
    dishes: {
      poha: { name: "Poha", hindi: "पोहा", cal: 250, p: 6, c: 45, f: 5, benefits: ["Quick breakfast", "Light meal", "Easy to digest"] },
      idli: { name: "Idli", hindi: "इडली", cal: 40, p: 1.5, c: 8, f: 0.2, benefits: ["Weight loss", "Probiotics", "Post-workout"] },
      dosa: { name: "Dosa", hindi: "डोसा", cal: 120, p: 3, c: 22, f: 2, benefits: ["Breakfast staple", "Energy boost"] },
      upma: { name: "Upma", hindi: "उपमा", cal: 220, p: 5, c: 40, f: 5, benefits: ["Satiating", "Vegetable-rich"] },
      paratha: { name: "Aloo Paratha", hindi: "आलू पराठा", cal: 250, p: 5, c: 35, f: 10, benefits: ["Traditional", "Energy"] },
      dal_rice: { name: "Dal Rice", hindi: "दाल चावल", cal: 350, p: 12, c: 65, f: 3, benefits: ["Complete protein", "Comfort food"] },
      rajma_rice: { name: "Rajma Chawal", hindi: "राजमा चावल", cal: 400, p: 15, c: 70, f: 4, benefits: ["High protein", "Iron", "Fiber"] },
      chole: { name: "Chole", hindi: "छोले", cal: 280, p: 12, c: 42, f: 6, benefits: ["Protein-rich", "Flavorful"] },
      palak_paneer: { name: "Palak Paneer", hindi: "पालक पनीर", cal: 280, p: 16, c: 12, f: 18, benefits: ["Iron", "Calcium", "Protein"] },
      chicken_curry: { name: "Chicken Curry", hindi: "चिकन करी", cal: 280, p: 32, c: 8, f: 12, benefits: ["High protein", "Muscle building"] },
      tandoori_chicken: { name: "Tandoori Chicken", hindi: "तंदूरी चिकन", cal: 220, p: 35, c: 5, f: 6, benefits: ["Lean protein", "Low fat"] },
      biryani: { name: "Chicken Biryani", hindi: "चिकन बिरयानी", cal: 550, p: 25, c: 70, f: 18, benefits: ["Post-workout", "Flavorful"] },
      makhana: { name: "Roasted Makhana", hindi: "मखाना", cal: 105, p: 3, c: 20, benefits: ["Low calorie snack", "Weight loss"] },
      dhokla: { name: "Dhokla", hindi: "ढोकला", cal: 160, p: 5, c: 30, benefits: ["Healthy snack", "Steamed", "Light"] },
    }
  },
  exercises: {
    chest: {
      benchPress: { name: "Barbell Bench Press", difficulty: "intermediate", primary: "Chest", secondary: ["Triceps", "Shoulders"], benefits: ["Mass", "Strength"] },
      pushups: { name: "Push-ups", difficulty: "beginner", primary: "Chest", equipment: "Bodyweight" },
      inclinePress: { name: "Incline Press", primary: "Upper Chest" },
      dips: { name: "Chest Dips", primary: "Lower Chest" },
    },
    back: {
      pullups: { name: "Pull-ups", primary: "Lats", difficulty: "intermediate" },
      deadlift: { name: "Deadlift", primary: "Entire Back", difficulty: "advanced" },
      rows: { name: "Barbell Rows", primary: "Mid Back" },
      latPulldown: { name: "Lat Pulldown", primary: "Lats" },
    },
    legs: {
      squat: { name: "Barbell Squat", primary: "Quads", secondary: ["Glutes", "Hamstrings"] },
      legPress: { name: "Leg Press", primary: "Quads" },
      lunges: { name: "Lunges", primary: "Glutes/Quads" },
      calfRaises: { name: "Calf Raises", primary: "Calves" },
    },
    shoulders: {
      overheadPress: { name: "Overhead Press", primary: "Shoulders" },
      lateralRaise: { name: "Lateral Raise", primary: "Side Delts" },
    },
    arms: {
      bicepCurl: { name: "Bicep Curls", primary: "Biceps" },
      tricepPushdown: { name: "Tricep Pushdown", primary: "Triceps" },
    },
    core: {
      plank: { name: "Plank", primary: "Core", benefits: ["Stability"] },
      legRaises: { name: "Leg Raises", primary: "Lower Abs" },
    }
  },
  principles: {
    muscle_building: "To build muscle (hypertrophy), focus on progressive overload, training each muscle 2x per week, 6-12 rep range, and consuming 1.8-2.2g of protein per kg of bodyweight.",
    fat_loss: "Fat loss requires a calorie deficit. Aim for 0.5-1kg loss per week. High protein is crucial to preserve muscle mass during a cut. Focus on whole foods and high fiber.",
    indian_pot_belly: "The 'Indian Pot Belly' is often due to high visceral fat from refined carbs (white rice, sugar). Switch to whole grains like brown rice or millets, increase protein, and add HIIT to your routine.",
    supplements: "Creatine Monohydrate (5g daily) is the most researched and effective supplement for strength. Whey protein helps meet protein targets. Vitamin D and B12 are also recommended for general health.",
    hydration: "Drink 3-4 liters of water daily. Dehydration can reduce performance by 20%. Water is essential for metabolism and joint health.",
    recovery: "Sleep 7-9 hours. Muscles grow during rest, not during the workout. Growth hormone release peaks during deep sleep.",
    protein_sources: "Best sources: Chicken Breast, Fish, Eggs (Non-Veg); Paneer, Tofu, Greek Yogurt, Lentils, Soya Chunks (Veg).",
    indian_breakfasts: "Healthy options: Oats Upma, Moong Dal Cheela, Vegetable Poha, Idli with Sambar, or Egg Bhurji with Whole Wheat Roti.",
  }
};
